# Generated by Django 5.0.2 on 2024-03-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_orderitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='countInStock',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
